```yaml
# Site settings
title: Simple HTML Outlook Instructions
description: A static website providing instructions on how to use Microsoft Outlook, including setup, email management, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://your-domain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
```